### ISSUE TITLE
TBB_INCLUDE_DIR is set to NOTFOUND

### ISSUE THREAD

**Issue by Zephyr06** [mive93/DAG-scheduling#1]
Hi, I am trying to compile your repo but found this error when configuring cmake. I guess "tbb/task_scheduler_init.h" is missing from the repo, do you have any suggestions? Thanks a lot!!

**Comment by mive93** [comment]
Hi @Zephyr06,

it is due to the submodule np-schedulability-analysis, it has among its [dependencies](https://github.com/brandenburg/np-schedulability-analysis/tree/0dc4b489b26d66c3ba0aba15b81353b5076784dc#dependencies)  the Intel Thread Building Blocks (TBB) library and parallel runtime.
I think that you should solve it just by

```
sudo apt install libtbb-dev
```

Let me know if that works.

**Comment by Zephyr06** [comment]
Yes, your suggestion works well, thanks a lot!
